"""Quorum evaluation and dependence decomposition on the RQ1 sweep.

Answers the two things the pooled phi contrast could not, both from the SAME per-repetition votes.

(1) DEPENDENCE, ALL REPETITIONS, UNIQUE UNORDERED PAIRS.  Nothing is collapsed to a modal vote:
    p_i(x) = (#approvals over the 3 repetitions)/3.  Every unordered pair is counted once.

    Because each cell was generated by an independent model run, votes are independent GIVEN the
    payload by construction of the experiment, so the covariance decomposes exactly:

        Cov(F_i, F_j) = E_x[Cov(F_i, F_j | x)] + Cov_x(p_i(x), p_j(x))
                      = 0  (independent runs)   + between-payload (shared-input) covariance

    We report both halves rather than claiming a model-lineage common cause the design cannot
    identify.  The measured dependence is shared-input dependence -- which is what a replicated
    quorum actually faces, since every replica reads the same injected content.

(2) QUORUM BEHAVIOUR.  For a member set Q and threshold q we compute, exactly (Poisson-binomial DP,
    no Monte-Carlo over votes):

        ASR_obs = E_x[ P(#approve >= q | per-payload rates p_i(x)) ]     what the quorum does
        ASR_ind = P(#approve >= q | member i at its POOLED MARGINAL rate p_i)   what a designer
                                                                        assuming independent
                                                                        member failures predicts

    Their ratio is the price of shared-input dependence at the quorum level.

Selection leakage: payloads are split 50/50 stratified by attack category.  Composition rules that
LOOK at data (lowest-ASR, best security-utility, max failure-vector diversity) select members on the
training half only; every strategy is scored on the held-out half.

Usage:  python -m decorrelation.analyze_quorum [--out decorrelation/quorum_analysis.json]
"""
from __future__ import annotations

import argparse
import glob
import itertools
import json
import os
import random
from dataclasses import dataclass

import numpy as np

from decorrelation.corpus_tdsc import build_tdsc_corpus
from decorrelation.model_matrix import MATRIX

HERE = os.path.dirname(__file__)
RQ1_DIR = os.path.join(HERE, "rq1")
DEFENSES = ["none", "spotlight", "struq", "hierarchy", "provenance", "known_answer"]
FAMILY = {m.tag: m.family for m in MATRIX}
PARAMS = {m.tag: m.params for m in MATRIX}
QUANT = {m.tag: m.quant for m in MATRIX}
SEED = 20260801


@dataclass(frozen=True)
class Agent:
    tag: str
    defense: str

    @property
    def family(self) -> str:
        return FAMILY[self.tag]

    @property
    def key(self) -> str:
        return f"{self.tag}|{self.defense}"


# ---------------------------------------------------------------- loading

def load_agents():
    """agent -> {channel: per-item approval RATE over the 3 repetitions}, plus the item order."""
    cells = {}
    for p in sorted(glob.glob(os.path.join(RQ1_DIR, "*.json"))):
        with open(p) as f:
            c = json.load(f)
        cells[(c["tag"], c["defense"])] = c

    first = next(iter(cells.values()))
    items = {"inj": sorted(first["raw"].keys()),
             "legit": sorted(first["raw_legit"].keys()),
             "ctrl": sorted(first["raw_controls"].keys())}
    src = {"inj": "raw", "legit": "raw_legit", "ctrl": "raw_controls"}

    agents, raw = {}, {}
    for (tag, defense), c in cells.items():
        if tag not in FAMILY:
            continue
        a = Agent(tag, defense)
        agents[a] = {}
        raw[a] = {}
        for ch, key in src.items():
            assert sorted(c[key].keys()) == items[ch], f"item-set mismatch {tag}/{defense}/{ch}"
            agents[a][ch] = np.array([np.mean(c[key][i]) for i in items[ch]], dtype=float)
            raw[a][ch] = np.array([c[key][i] for i in items[ch]], dtype=float)   # [items, reps]
    return agents, raw, items


def category_of(items_inj: list[str]) -> dict[str, str]:
    cases = {c.cid: c for c in build_tdsc_corpus()}
    return {cid: cases[cid].category for cid in items_inj if cid in cases}


def stratified_split(items_inj: list[str], cats: dict[str, str], seed: int = SEED):
    """50/50 payload split stratified by attack category."""
    rng = random.Random(seed)
    by_cat: dict[str, list[int]] = {}
    for i, cid in enumerate(items_inj):
        by_cat.setdefault(cats.get(cid, "?"), []).append(i)
    train, test = [], []
    for c in sorted(by_cat):
        idx = by_cat[c][:]
        rng.shuffle(idx)
        h = len(idx) // 2
        train += idx[:h]
        test += idx[h:]
    return np.array(sorted(train)), np.array(sorted(test))


# ---------------------------------------------------------------- Poisson-binomial

def pb_dist(probs: np.ndarray) -> np.ndarray:
    """Full distribution of #approvals for each row of `probs` [items, N] -> [items, N+1]."""
    n_items, n = probs.shape
    dist = np.zeros((n_items, n + 1))
    dist[:, 0] = 1.0
    for i in range(n):
        p = probs[:, i][:, None]
        sh = np.zeros_like(dist)
        sh[:, 1:] = dist[:, :-1]
        dist = dist * (1 - p) + sh * p
    return dist


def pb_tail(probs: np.ndarray, t: int) -> np.ndarray:
    return pb_dist(probs)[:, t:].sum(axis=1)


# ---------------------------------------------------------------- repetition stability

def rep_stability(raw, agents) -> dict:
    """Quantifies exactly what a modal-vote collapse would have discarded (blueprint 6.1)."""
    out = {}
    for ch in ("inj", "legit", "ctrl"):
        k = np.concatenate([raw[a][ch].sum(axis=1) for a in agents])   # #approvals in {0..3}
        n = len(k)
        out[ch] = {
            "n_cells": int(n),
            "unanimous_frac": float(np.mean((k == 0) | (k == 3))),
            "split_2_1_frac": float(np.mean((k == 1) | (k == 2))),
            "mean_within_cell_variance": float(np.mean((k / 3) * (1 - k / 3))),
        }
    return out


# ---------------------------------------------------------------- dependence by pair category

PAIR_CLASSES = [
    "same config, same defense (replica)",
    "same config, different quantization",
    "same family, different size, same defense",
    "same family, defense-diverse",
    "family-diverse, same defense",
    "family-diverse, defense-diverse",
]


def pair_class(a: Agent, b: Agent) -> str:
    same_fam, same_def = a.family == b.family, a.defense == b.defense
    if a.tag == b.tag and same_def:
        return PAIR_CLASSES[0]
    base_a = a.tag.split("-instruct")[0].split(":")[0] + ":" + a.tag.split(":")[1].split("-")[0]
    base_b = b.tag.split("-instruct")[0].split(":")[0] + ":" + b.tag.split(":")[1].split("-")[0]
    if same_def and same_fam and base_a == base_b and QUANT[a.tag] != QUANT[b.tag]:
        return PAIR_CLASSES[1]
    if same_fam and same_def:
        return PAIR_CLASSES[2]
    if same_fam and not same_def:
        return PAIR_CLASSES[3]
    if not same_fam and same_def:
        return PAIR_CLASSES[4]
    return PAIR_CLASSES[5]


def dependence_table(agents, pool: list[Agent], item_idx: np.ndarray, n_boot: int = 1000) -> dict:
    """Per pair category: P(Fi), P(Fj), joint, product, excess, lift, phi, OR, Jaccard.
    Each unordered pair counted ONCE. Two-way (payload x pair) cluster bootstrap."""
    P = np.vstack([agents[a]["inj"][item_idx] for a in pool])
    n_items = P.shape[1]

    pairs = [(i, j) for i, j in itertools.combinations(range(len(pool)), 2)]
    classes = [pair_class(pool[i], pool[j]) for i, j in pairs]
    # a replica pair is one configuration instantiated twice: two independent draws from p_i(x)
    pairs += [(i, i) for i in range(len(pool))]
    classes += [PAIR_CLASSES[0]] * len(pool)
    pa = np.array(pairs)
    classes = np.array(classes)
    Pi, Pj = P[pa[:, 0]], P[pa[:, 1]]
    prod = Pi * Pj
    union = Pi + Pj - prod

    def stats_for(ii, pi_):
        pi, pj = Pi[np.ix_(pi_, ii)], Pj[np.ix_(pi_, ii)]
        pr, un = prod[np.ix_(pi_, ii)], union[np.ix_(pi_, ii)]
        cls = classes[pi_]
        mi, mj, J, U = pi.mean(1), pj.mean(1), pr.mean(1), un.mean(1)
        res = {}
        for c in PAIR_CLASSES:
            m = cls == c
            if not m.any():
                continue
            MI, MJ, JJ, UU = mi[m].mean(), mj[m].mean(), J[m].mean(), U[m].mean()
            I_ = MI * MJ
            den = np.sqrt(MI * (1 - MI) * MJ * (1 - MJ))
            b, cc, d = MI - JJ, MJ - JJ, 1 - MI - MJ + JJ
            degenerate = b < 1e-4 or cc < 1e-4
            res[c] = {"p_i": float(MI), "p_j": float(MJ), "joint": float(JJ), "indep": float(I_),
                      "excess": float(JJ - I_), "lift": float(JJ / I_) if I_ > 0 else float("nan"),
                      "phi": float((JJ - I_) / den) if den > 0 else float("nan"),
                      "odds_ratio": float("nan") if degenerate else float((JJ * d) / (b * cc)),
                      "or_degenerate": bool(degenerate),
                      "jaccard": float(JJ / UU) if UU > 0 else float("nan"),
                      "n_pairs": int(m.sum())}
        return res

    point = stats_for(np.arange(n_items), np.arange(len(pairs)))
    rng = np.random.default_rng(SEED)
    keys = ("joint", "excess", "lift", "phi", "jaccard")
    boots = {c: {k: [] for k in keys} for c in point}
    for _ in range(n_boot):
        s = stats_for(rng.integers(0, n_items, n_items), rng.integers(0, len(pairs), len(pairs)))
        for c, v in s.items():
            if c in boots:
                for k in keys:
                    boots[c][k].append(v[k])
    for c in point:
        for k in keys:
            lo, hi = np.percentile(boots[c][k], [2.5, 97.5])
            point[c][f"{k}_ci"] = [float(lo), float(hi)]

    total = float(np.mean(prod.mean(1) - Pi.mean(1) * Pj.mean(1)))
    between = float(np.mean([np.cov(Pi[k], Pj[k], bias=True)[0, 1] for k in range(len(pairs))]))
    return {"classes": point,
            "decomposition": {"total_covariance": total, "between_payload_covariance": between,
                              "within_payload_covariance": total - between}}


def dependence_agent_cluster(agents, pool: list[Agent], n_boot: int = 1000) -> dict:
    """Primary uncertainty estimate: two-way (AGENT x payload) cluster bootstrap.

    Pair observations reuse agents -- every configuration appears in many pairs -- so resampling
    pairs alone understates uncertainty. Here each replicate resamples AGENTS with replacement and
    payloads with replacement, then rebuilds every unordered pair among the resampled agents. This
    is the dyadic ("pigeonhole") cluster bootstrap and is the interval we report.
    """
    P = np.vstack([agents[a]["inj"] for a in pool])
    nX = P.shape[1]
    rng = np.random.default_rng(SEED)

    def one(agent_idx, item_idx):
        Q = P[np.ix_(agent_idx, item_idx)]
        marg = Q.mean(axis=1)
        acc = {c: [[], [], []] for c in PAIR_CLASSES}     # joint, indep, phi-denominator pieces
        for u, v in itertools.combinations_with_replacement(range(len(agent_idx)), 2):
            c = pair_class(pool[agent_idx[u]], pool[agent_idx[v]])
            if u == v and c != PAIR_CLASSES[0]:
                continue
            acc[c][0].append(float(np.mean(Q[u] * Q[v])))
            acc[c][1].append(float(marg[u] * marg[v]))
            acc[c][2].append((float(marg[u]), float(marg[v])))
        out = {}
        for c, (J, I_, M) in acc.items():
            if not J:
                continue
            JJ, II = float(np.mean(J)), float(np.mean(I_))
            MI = float(np.mean([m[0] for m in M]))
            MJ = float(np.mean([m[1] for m in M]))
            den = np.sqrt(MI * (1 - MI) * MJ * (1 - MJ))
            out[c] = {"joint": JJ, "indep": II, "excess": JJ - II,
                      "lift": JJ / II if II > 0 else float("nan"),
                      "phi": (JJ - II) / den if den > 0 else float("nan"),
                      "n_pairs": len(J)}
        return out

    point = one(np.arange(len(pool)), np.arange(nX))
    keys = ("joint", "excess", "lift", "phi")
    boots = {c: {k: [] for k in keys} for c in point}
    for _ in range(n_boot):
        s = one(rng.integers(0, len(pool), len(pool)), rng.integers(0, nX, nX))
        for c in boots:
            if c in s:
                for k in keys:
                    boots[c][k].append(s[c][k])
    for c in point:
        for k in keys:
            v = [x for x in boots[c][k] if np.isfinite(x)]
            if v:
                lo, hi = np.percentile(v, [2.5, 97.5])
                point[c][f"{k}_ci"] = [float(lo), float(hi)]
    return point


# ---------------------------------------------------------------- quorum composition

def thresholds_for(n: int) -> list[tuple[str, int]]:
    out, seen = [], set()
    for name, t in (("1-of-N", 1), ("2-of-N", 2), ("majority", n // 2 + 1),
                    ("supermajority", -(-2 * n // 3)), ("unanimity", n)):
        if 1 <= t <= n and t not in seen:
            seen.add(t)
            out.append((f"{name} (q={t})", t))
    return out


STRATEGIES = ["homogeneous", "same-family-diff-size", "family-diverse", "defense-diverse",
              "joint-diverse", "random", "lowest-ASR", "best-security-utility", "max-diversity"]
DATA_DRIVEN = {"lowest-ASR", "best-security-utility", "max-diversity"}


def _fill(pick, pool, n, rng):
    while len(pick) < n:
        pick.append(rng.choice(pool))
    return pick[:n]


def member_sets(agents, pool: list[Agent], strategy: str, n: int, k: int,
                rng: random.Random, train_idx: np.ndarray) -> list[list[Agent]]:
    by_fam, by_def, by_tag = {}, {}, {}
    for a in pool:
        by_fam.setdefault(a.family, []).append(a)
        by_def.setdefault(a.defense, []).append(a)
        by_tag.setdefault(a.tag, []).append(a)
    fams, defs, tags = sorted(by_fam), sorted(by_def), sorted(by_tag)

    if strategy in DATA_DRIVEN:
        # selection uses TRAINING payloads only; scoring happens on the held-out half
        asr = {a: agents[a]["inj"][train_idx].mean() for a in pool}
        util = {a: agents[a]["legit"].mean() for a in pool}
        if strategy == "lowest-ASR":
            order = sorted(pool, key=lambda a: (asr[a], -util[a]))
            return [order[:n]] * 1
        if strategy == "best-security-utility":
            order = sorted(pool, key=lambda a: -(util[a] - asr[a]))
            return [order[:n]] * 1
        # max-diversity: greedily minimise mean pairwise agreement of training failure vectors
        V = {a: agents[a]["inj"][train_idx] for a in pool}
        seed_a = min(pool, key=lambda a: (asr[a], -util[a]))
        chosen = [seed_a]
        while len(chosen) < n:
            best, best_score = None, None
            for a in pool:
                if a in chosen:
                    continue
                sc = np.mean([float(np.mean(V[a] * V[c])) for c in chosen])
                if best_score is None or sc < best_score:
                    best, best_score = a, sc
            chosen.append(best)
        return [chosen]

    out, guard = [], 0
    while len(out) < k and guard < k * 200:
        guard += 1
        try:
            if strategy == "homogeneous":
                out.append([rng.choice(pool)] * n)
            elif strategy == "same-family-diff-size":
                f = rng.choice(fams)
                d = rng.choice(defs)
                cand = [a for a in by_fam[f] if a.defense == d]
                if len({a.tag for a in cand}) < 2:
                    continue
                pick = rng.sample(cand, min(n, len(cand)))
                out.append(_fill(pick, cand, n, rng))
            elif strategy == "defense-diverse":
                t = rng.choice(tags)
                cand = by_tag[t]
                out.append(_fill(rng.sample(cand, min(n, len(cand))), cand, n, rng))
            elif strategy == "family-diverse":
                d = rng.choice(defs)
                cand = by_def[d]
                picked_f = rng.sample(fams, min(n, len(fams)))
                pick = [rng.choice([a for a in cand if a.family == f]) for f in picked_f]
                out.append(_fill(pick, cand, n, rng))
            elif strategy == "joint-diverse":
                pf = rng.sample(fams, min(n, len(fams)))
                pd = rng.sample(defs, min(n, len(defs)))
                while len(pf) < n:
                    pf.append(rng.choice(fams))
                while len(pd) < n:
                    pd.append(rng.choice(defs))
                pick = [rng.choice([a for a in pool if a.family == f and a.defense == d])
                        for f, d in zip(pf, pd)]
                out.append(pick)
            elif strategy == "random":
                out.append([rng.choice(pool) for _ in range(n)])
            else:
                raise ValueError(strategy)
        except (ValueError, IndexError):
            continue
    return out


def quorum_eval(agents, pool, test_idx, train_idx, sizes=(3, 5, 7),
                k_sets=200, n_boot=400) -> list[dict]:
    rng = random.Random(SEED)
    boot_rng = np.random.default_rng(SEED)
    nX = len(test_idx)
    boots = [boot_rng.integers(0, nX, nX) for _ in range(n_boot)]
    rows = []
    for n in sizes:
        for strat in STRATEGIES:
            sets = member_sets(agents, pool, strat, n, k_sets, rng, train_idx)
            if not sets:
                continue
            Pinj = np.stack([np.stack([agents[a]["inj"][test_idx] for a in Q], 1) for Q in sets])
            Pleg = np.stack([np.stack([agents[a]["legit"] for a in Q], 1) for Q in sets])
            Pctl = np.stack([np.stack([agents[a]["ctrl"] for a in Q], 1) for Q in sets])
            marg = Pinj.mean(axis=1)
            dist_i = np.stack([pb_dist(Pinj[s]) for s in range(len(sets))])   # [k, X, N+1]
            dist_l = np.stack([pb_dist(Pleg[s]) for s in range(len(sets))])
            # escalate-on-disagreement policy: act only on a unanimous quorum, else ask a human
            esc = {"unanimous_approve_attack": float(dist_i[:, :, n].mean()),
                   "unanimous_approve_legit": float(dist_l[:, :, n].mean()),
                   "human_rate_attack": float(1 - dist_i[:, :, n].mean() - dist_i[:, :, 0].mean()),
                   "human_rate_legit": float(1 - dist_l[:, :, n].mean() - dist_l[:, :, 0].mean())}
            for tname, t in thresholds_for(n):
                asr_x = dist_i[:, :, t:].sum(axis=2)
                util_x = dist_l[:, :, t:].sum(axis=2)
                ctl_x = np.stack([pb_tail(Pctl[s], t) for s in range(len(sets))])
                asr_ind = np.array([pb_tail(marg[s][None, :], t)[0] for s in range(len(sets))])
                asr_obs = asr_x.mean(axis=1)
                b_obs, b_lift = [], []
                for bi in boots:
                    o = asr_x[:, bi].mean(axis=1)
                    m = Pinj[:, bi, :].mean(axis=1)
                    i_ = np.array([pb_tail(m[s][None, :], t)[0] for s in range(len(sets))])
                    b_obs.append(o.mean())
                    b_lift.append(o.mean() / max(i_.mean(), 1e-12))
                rows.append({
                    "N": n, "threshold": tname, "q": t, "strategy": strat, "n_sets": len(sets),
                    "asr_obs": float(asr_obs.mean()),
                    "asr_obs_ci": [float(np.percentile(b_obs, 2.5)), float(np.percentile(b_obs, 97.5))],
                    "asr_indep": float(asr_ind.mean()),
                    "gap": float(asr_obs.mean() - asr_ind.mean()),
                    "lift": float(asr_obs.mean() / max(asr_ind.mean(), 1e-12)),
                    "lift_ci": [float(np.percentile(b_lift, 2.5)), float(np.percentile(b_lift, 97.5))],
                    "utility": float(util_x.mean()),
                    "false_denial": float(1 - util_x.mean()),
                    "control_fp": float(ctl_x.mean()),
                    "reliable_defeat_frac": float((asr_x >= 0.5).mean()),
                    "inferences": n, **{f"esc_{k}": v for k, v in esc.items()},
                })
    return rows


def single_agent_baselines(agents, pool, test_idx, train_idx) -> list[dict]:
    """N=1 reference points. Selection on the training half, scoring on the held-out half."""
    tr = {a: (agents[a]["inj"][train_idx].mean(), agents[a]["legit"].mean()) for a in pool}
    def row(label, a):
        return {"N": 1, "threshold": "n/a", "q": 1, "strategy": label, "n_sets": 1,
                "asr_obs": float(agents[a]["inj"][test_idx].mean()),
                "asr_indep": float(agents[a]["inj"][test_idx].mean()), "lift": 1.0, "gap": 0.0,
                "utility": float(agents[a]["legit"].mean()),
                "false_denial": float(1 - agents[a]["legit"].mean()),
                "control_fp": float(agents[a]["ctrl"].mean()), "inferences": 1, "agent": a.key}
    lowest = min(pool, key=lambda a: tr[a][0])
    usable = [a for a in pool if tr[a][1] >= 0.80]
    best_su = max(pool, key=lambda a: tr[a][1] - tr[a][0])
    med = sorted(pool, key=lambda a: tr[a][0])[len(pool) // 2]
    out = [row("single: lowest train ASR (degenerate refuser)", lowest),
           row("single: best train security-utility", best_su),
           row("single: median train ASR", med)]
    if usable:
        out.insert(1, row("single: lowest train ASR s.t. utility>=80%",
                          min(usable, key=lambda a: tr[a][0])))
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(HERE, "quorum_analysis.json"))
    ap.add_argument("--boot", type=int, default=1000)
    ap.add_argument("--sets", type=int, default=200)
    args = ap.parse_args()

    agents, raw, items = load_agents()
    cats = category_of(items["inj"])
    train_idx, test_idx = stratified_split(items["inj"], cats)
    print(f"{len(agents)} agents | items {len(items['inj'])} inj / {len(items['legit'])} legit / "
          f"{len(items['ctrl'])} ctrl | split {len(train_idx)} train / {len(test_idx)} held-out")

    stab = rep_stability(raw, agents)
    print("\nrepetition stability (what a modal collapse discards):")
    for ch, v in stab.items():
        print(f"  {ch:<6} unanimous={v['unanimous_frac']*100:.1f}%  2-1 split={v['split_2_1_frac']*100:.1f}%")

    # deployable pool excludes the undefended agent: no deployment ships an agent with no defense
    pool = sorted([a for a in agents if a.defense != "none"], key=lambda a: a.key)
    allpool = sorted(agents, key=lambda a: a.key)
    print(f"\ndeployable pool: {len(pool)} agents (5 defenses x 13 configs)")

    dep = dependence_table(agents, pool, np.arange(len(items["inj"])), n_boot=args.boot)
    dep_all = dependence_table(agents, allpool, np.arange(len(items["inj"])), n_boot=200)
    print("\ndependence by pair category (deployable pool, all repetitions, unique unordered pairs):")
    for c, v in dep["classes"].items():
        print(f"  {c:<44} joint={v['joint']:.4f} indep={v['indep']:.4f} lift={v['lift']:.3f} "
              f"[{v['lift_ci'][0]:.3f},{v['lift_ci'][1]:.3f}] phi={v['phi']:.4f} "
              f"[{v['phi_ci'][0]:.4f},{v['phi_ci'][1]:.4f}] n={v['n_pairs']}")
    d = dep["decomposition"]
    print(f"  decomposition: total={d['total_covariance']:.5f} "
          f"between-payload={d['between_payload_covariance']:.5f} "
          f"within-payload={d['within_payload_covariance']:.2e}")

    dep_ac = dependence_agent_cluster(agents, pool, n_boot=min(400, args.boot))
    print("\nPRIMARY intervals -- two-way (agent x payload) cluster bootstrap:")
    for c, v in dep_ac.items():
        print(f"  {c:<44} lift={v['lift']:.3f} [{v['lift_ci'][0]:.3f},{v['lift_ci'][1]:.3f}]  "
              f"phi={v['phi']:.4f} [{v['phi_ci'][0]:.4f},{v['phi_ci'][1]:.4f}]  n={v['n_pairs']}")

    base = single_agent_baselines(agents, pool, test_idx, train_idx)
    rows = quorum_eval(agents, pool, test_idx, train_idx,
                       k_sets=args.sets, n_boot=max(200, args.boot // 3))

    print("\nquorum evaluation on the held-out payload half:")
    print(f"{'N':>2} {'threshold':<20} {'strategy':<22} {'ASR':>7} {'ASR_ind':>8} {'lift':>6} "
          f"{'util':>7} {'ctlFP':>7} {'det':>6}")
    for r in base:
        print(f"{r['N']:>2} {r['threshold']:<20} {r['strategy'][:22]:<22} {r['asr_obs']*100:6.1f}% "
              f"{'--':>8} {'--':>6} {r['utility']*100:6.1f}% {r['control_fp']*100:6.1f}% {'--':>6}")
    for r in rows:
        print(f"{r['N']:>2} {r['threshold']:<20} {r['strategy'][:22]:<22} {r['asr_obs']*100:6.1f}% "
              f"{r['asr_indep']*100:7.1f}% {r['lift']:6.2f} {r['utility']*100:6.1f}% "
              f"{r['control_fp']*100:6.1f}% {r['reliable_defeat_frac']*100:5.1f}%")

    with open(args.out, "w") as f:
        json.dump({"dependence": dep, "dependence_all_agents": dep_all,
                   "dependence_agent_cluster": dep_ac,
                   "rep_stability": stab, "quorum": rows, "baselines": base,
                   "meta": {"seed": SEED, "n_agents": len(agents), "n_pool": len(pool),
                            "boot": args.boot, "sets_per_cell": args.sets,
                            "n_train": int(len(train_idx)), "n_test": int(len(test_idx)),
                            "items": {k: len(v) for k, v in items.items()}}}, f, indent=2)
    print(f"\nwrote {args.out}")


if __name__ == "__main__":
    main()
